<?php $this->layout('layout::default', ['title' => 'ConfirmView']) ?>

    <div class="govuk-width-container">
        <div class="govuk-phase-banner">
            <p class="govuk-phase-banner__content"><strong class="govuk-tag govuk-phase-banner__content__tag ">
                    alpha
                </strong>
                <span class="govuk-phase-banner__text">
                    This is a new service – your
                    <a class="govuk-link" href="#">feedback</a> will help us to improve it.
                </span>
            </p>
        </div>
        <a href="home.html" class="govuk-back-link">Back</a>

        <main class="govuk-main-wrapper">

            <div class="govuk-grid-row">
                <div class="govuk-grid-column-one-half">
                    <h1 class="govuk-heading-xl">Confirmation</h1>

                        <div class="govuk-details_text govuk-body">
                            By continuing, you are confirming << Name >> shared following LPA with you and that you are authorised to view it:
                        </div>


                        <table class="govuk-table">
                            <tr class="govuk-table__row">
                                <th class="govuk-table__header" scope="row"></th>
                                <td class="govuk-table__cell"></td>
                            </tr>
                            <tr class="govuk-table__row">
                                <th class="govuk-table__header" scope="row">Type of LPA</th>
                                <td class="govuk-table__cell"><< Health and Welfare >></td>
                            </tr>
                            <tr class="govuk-table__row">
                                <th class="govuk-table__header" scope="row">Donor name</th>
                                <td class="govuk-table__cell"></td>
                            </tr>
                            </tbody>
                        </table>

                        <div class="govuk-form-group">
                            <div class="govuk-checkboxes">
                                <div class="govuk-checkboxes__item">
                                    <input class="govuk-checkboxes__input" id="confirm_view_LPA" name="confirm_view_LPA" type="checkbox" value="carcasses">
                                    <label class="govuk-label govuk-checkboxes__label" for="confirm_view_LPA">
                                        I confirm I am authorised to view this LPA
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="govuk-details_text govuk-body">
                                If any of the information above is incorrect, please contact us on 02342 435920.
                        </div>


                        <button type="submit" class="govuk-button">
                            Continue
                        </button>
                </div>
            </div>

        </main>
    </div>
