<?php $this->layout('layout::default', ['title' => 'Home']) ?>

    <div class="govuk-width-container">
        <div class="govuk-phase-banner">
            <p class="govuk-phase-banner__content"><strong class="govuk-tag govuk-phase-banner__content__tag ">
                    alpha
                </strong>
                <span class="govuk-phase-banner__text">
                    This is a new service – your
                    <a class="govuk-link" href="#">feedback</a> will help us to improve it.
                </span>
            </p>
        </div>
        <a href="home.html" class="govuk-back-link">Back</a>

        <main class="govuk-main-wrapper">


<!--            <div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" tabindex="-1" data-module="error-summary">-->
<!--                <h2 class="govuk-error-summary__title" id="error-summary-title">-->
<!--                    There is a problem-->
<!--                </h2>-->
<!--                <div class="govuk-error-summary__body">-->
<!--                    <ul class="govuk-list govuk-error-summary__list">-->
<!--                        <li>-->
<!--                            <a href="#donor-surname-error">The name field cannot be empty. Please provide your name</a>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </div>-->
<!--            </div>-->

            <div class="govuk-grid-row">
                <div class="govuk-grid-column-one-half">
                    <h1 class="govuk-heading-xl">Enter</h1>

                    <form method="post">
                        <fieldset class="govuk-fieldset">

<!--                            <span id="donor-surname-error" class="govuk-error-message">-->
<!--                                 <span class="govuk-visually-hidden">Error:</span> The name field cannot be empty-->
<!--                            </span>-->
    
                            <div class="govuk-form-group">
                                <label class="govuk-label" for="donor-surname">
                                    Donor's surname
                                </label>
                                <input class="govuk-input" id="donor-surname" name="donor-surname" type="text">
                            </div>
    
                            <div class="govuk-form-group">
                                <label class="govuk-label" for="share-code">
                                    Share code
                                </label>
                                <input class="govuk-input govuk-input--width-10" id="share-code-one" name="share-code-one"
                                    type="text">
                                /
                                <input class="govuk-input govuk-input--width-10" id="share-code-two" name="share-code-two"
                                    type="text" style="width: 48%;">
                            </div>
    
                            <details class="govuk-details">
                                <summary class="govuk-details__summary">
                                    <span class="govuk-details__summary-text">
                                        What is a share code?
                                    </span>
                                </summary>
                                <div class="govuk-details__text">
                                    A share code is given to you by the donor or an attorney named on the lasting power
                                    of
                                    attorney.
                                </div>
                            </details>
    
                            <button type="submit" class="govuk-button">Save and continue</button>
                        </fieldset>
                    </form>
                </div>
            </div>

        </main>
    </div>
